### ISSUE TITLE
Finish moving 3rd party player and css files into the asset pipeline

### ISSUE THREAD

**Issue by vichudson1** [vichudson1/empire#16]
All of the 3rd party assets for the player need to be switched from the min versions to regular and moved into the pipeline to be concatenated and minified when the site is built.

**Comment by scottaw66** [comment]
Working on this now (tromping all over you now) but I may have some questions about the many css files linked to for the player.

**Comment by vichudson1** [comment]
The switch to using the unminified version of the media elements scripts and css files and having the pipeline concat and minify them would be a great way to utilize the new [Hugo Modules](https://www.thenewdynamic.com/article/hugo-modules-everything-from-imports-to-create/) functionality @scottaw66

**Comment by vichudson1** [comment]
On second thought maybe we don’t want modules. I just read [here](https://discourse.gohugo.io/t/hugo-modules-for-dummies/20758), that we’d need to have Go installed to use modules.

Thoughts, @scottaw66?

**Comment by vichudson1** [comment]
Done 😃
