### ISSUE TITLE
Custom includes to HTML head on all layouts.

### ISSUE THREAD

**Issue by vichudson1** [vichudson1/empire#22]
There needs to be a way to add custom meta tags and scripts/includes to the html head element of pages. For instance iTunes meta tags to prevent the issue in the attached image. ![image](https://user-images.githubusercontent.com/4630697/103709374-6727c580-4f80-11eb-99eb-5b5acb21317c.jpeg) Note the BSTV iTunes link on an episode of BS Proper. 

We should add a new section to baseof.html that defines a "meta" section similar to title. Then the various layouts can just specify what goes in there. This will offer a way to inject custom meta data to the various layouts. It will also be crucial when we adopt Twitter cards as the different layout types won't all support the same Twitter card fields.

**Comment by scottaw66** [comment]
Vic, I think this one is complete. Please check out my commits related to includes and meta tags (2850755 and 7baba65)
