### ISSUE TITLE
Define & Create Archetypes

### ISSUE THREAD

**Issue by vichudson1** [vichudson1/empire#4]
We need Archtypes for each of these. We can start creating them and also use them as our scratchpad for the needed front matter values of each type. They can also serve as documentation for the various types until we can make proper documentation.

* Episode
* Podcast
* Aggregated Podcast
* Host
* Guest

*For the podcast and aggregated podcast, I want to use the feature that lets you have an Archetype directory of files. A simple Hugo new command will get you a new show folder, index.md and episode 1 md file.*

**Comment by vichudson1** [comment]
I’m starting these so we’ll have a place to document front matter paremters as we go.

**Comment by scottaw66** [comment]
These are done. We may modify them in the future, but they are done.
