### ISSUE TITLE
Social & Connect Buttons

### ISSUE THREAD

**Issue by vichudson1** [vichudson1/empire#6]
We need social icons for connecting to the shows and hosts.

There will be logic in the templates to do a lookup and use the appropriate contact url where appropriate. Lookup will go as follows.

1) Current Page - *Hosts*
2) Current Section - Shows
3) Site Params

This lookup order will allow for leaving fields blank if they aren't needed for a page type and defaulting to the first valid value found in the lookup. Everything in theory should connect to something, if all else fails they'll connect to the network itself.

**Comment by vichudson1** [comment]
I put them on the page and am turning them over to @scottaw66 for styling. Once that's done, I can put the logic into place to determine when they are visible and what the socials link to.

**Comment by scottaw66** [comment]
Socials are done, with searching set up for podcast, parent, site, using them in that order. Social options are set up in socials.json and are automatically added to new podcast and person (host, guest) pages when they’re generated from archetype.
