### ISSUE TITLE
Add Search For Content To Websites

### ISSUE THREAD

**Issue by vichudson1** [vichudson1/empire#9]
This [link](https://blog.jeremylikness.com/blog/dynamic-search-in-a-static-hugo-website/) could be a solution.

**Comment by scottaw66** [comment]
Also:
[How-to: Hugo Search + Lunr + Gulp - tips & tricks](https://discourse.gohugo.io/t/how-to-hugo-search-lunr-gulp/13342)
[Seach for your Hugo website](https://gohugo.io/tools/search/)

**Comment by scottaw66** [comment]
This is pretty much done unless we want to go back and tweak the search algorithm
